server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

      routes:
        # 1. Internal Endpoints Protection — BLOCKED AT GATEWAY
        - id: deny-internal-access
          uri: no://op
          predicates:
            - Path=/internal/**
          filters:
            - name: DenyPublicAccess

        # 2. Account Service Routes
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**, /api/v1/accounts/**
          filters:
            - name: JwtAuth
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"

        # 3. Transaction Service Routes
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/v1/transactions/**
          filters:
            - name: JwtAuth
            - name: IdempotencyKeyRequired
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@userKeyResolver}"

        # 4. Ledger Service Routes
        - id: ledger-service
          uri: lb://ledger-service
          predicates:
            - Path=/api/v1/ledger/**
          filters:
            - name: JwtAuth

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

jwt:
  public-key-path: classpath:keys/public.pem

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    com.paycore.apigateway: INFO
